---
# vi: set ft=yaml.ansible :
- name: update sources.list
  become: true
  replace:
    path: /etc/apt/sources.list
    regexp: 'http://archive.ubuntu.com/ubuntu'
    replace: 'http://ftp.riken.go.jp/Linux/ubuntu'
    backup: yes

- name: Update all packages to the latest version
  become: true
  apt:
    upgrade: dist

- name: Update all packages to the latest version
  become: true
  apt:
    update_cache: yes
    upgrade: dist

- name: install dependences for debian/ubuntu
  become: true
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - autoconf
    - automake
    - build-essential
    - cproto
    - gettext
    - git
    - libacl1-dev
    - libgpm-dev
    - liblua5.2-dev
    - libluajit-5.1-dev
    - libperl-dev
    - libtinfo-dev
    - lua5.2
    - luajit
    - ncurses-dev
    - python-dev
    - python3-dev
    - ruby-dev
